server {
    listen 80; #容器内部监听80端口
    server_name _; #接受任何域名/IP

    root /usr/share/nginx/html; #前端文件放在容器里的这个目录
    index index.html; #默认首页是index.html

    # Vue history mode fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
    #作用:当你访问http://你的IP/,Nginx会返回index.html.

    # Reverse proxy to FastAPI service in docker network
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    #作用:当请求路径是/api/xxx时,转发给FastAPI容器(backend:8000).

}

#nginx.conf是一个专门给Docker容器用的Nginx配置文件,不是安装在服务器上的那个Nginx,它是前端容器自带的Nginx.

#后端在部署后是一个进程,前端在部署后不是一个进程,而是一堆静态文件,这是前后端分离架构中最核心的区别之一.
#那么谁来"服务"这些静态文件?需要一个静态文件服务器.
#诶,Nginx直接托管是最推荐,性能最高的做法.